name: movie_and_series
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Geçerli ve geniş bir sürüm aralığı

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0 # HTTP istekleri için
  provider: ^6.0.5 # Durum yönetimi için
  json_annotation: ^4.8.1 # JSON veri modellemesi için
  intl: ^0.20.2
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6 # Otomatik kod oluşturmak için
  json_serializable: ^6.7.1 # JSON modellemeyi otomatikleştirir

flutter:
  uses-material-design: true